#! /bin/bash

function fHelp() {
	echo "  >> help"
	echo "  >> $0 jas_file"
	echo "  >>    jas_file :	ivjm language file with your code (no extention)" 
}

function fLaunch() {
	echo "  >> assemble the Micro program mic1ivjm ... "
	java -cp classes.zip mic1asm mic1ijvm.mal mic1ijvm.mic1
	echo "  >> assemble the IJVM program for $1 ..."
	java -cp classes.zip ijvmasm "source_jas/$1.jas" "source_ijvm/$1.ijvm"
	echo "  >> running the Simulator mic1ijvm on $1 ... "
	java -cp classes.zip  mic1sim mic1ijvm.mic1 "source_ijvm/$1.ijvm" & 
}

#main
echo "==== build and run MIC-1 simulation ===="
if [ $# -eq 1 ]; then
	fLaunch $@
else
	fHelp $0
fi

